server:
  port: 8089
spring:
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/task_manage_x?useUnicode=true&characterEncoding=utf-8
   username: root
   password: root
mybatis:
 type-aliases-package: com.cj.task.entity
 mapper-locations: classpath:mapper/*.xml